services: 
  navis_yolo:
    image: navis_yolo:latest
    container_name: navis_yolo
    command: ["/bin/bash"]
    network_mode: host
    runtime: nvidia
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /$XAUTH:$XAUTH
      - /dev/bus/usb:/dev/bus/usb
      - /dev/shm:/dev/shm
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=$XAUTH
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Set the required capabilities (e.g., for CUDA)
    shm_size: '8gb'
    stdin_open: true
    tty: true
    